5th commit

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -71,12 +71,12 @@ jobs:
          
       - name: Run Docker containter
         run: |
-         docker run -d -p 80:80 my_flask_app
+         docker run -d -p 5000:5000 my_flask_app
           
       - name: Test Hello Marshall
         run: |
           sleep 5  # Wait for the app to start
-          curl -f http://localhost:80 || exit 1  # Fail if the app doesn't respond
+          curl -f http://localhost:5000 || exit 1  # Fail if the app doesn't respond
             
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
